### ISSUE TITLE
其实我用的是pop这个库做的 哈哈

### ISSUE THREAD

**Issue by Rogue24** [MaterYi/-InfiteeAnimation#1]

**Comment by EtherealYi** [comment]
Infintee的工程师

**Comment by EtherealYi** [comment]
Infintee的工程师？

**Comment by Rogue24** [comment]
是的😄

发自我的iPhone

在 2020年3月10日，下午3:28，MasterYi <notifications@github.com> 写道：

﻿

Infintee的工程师？

**Comment by EtherealYi** [comment]
大神有联系方式么？我有几个动画效果一直没研究出来怎么实现，想请教下。

**Comment by Rogue24** [comment]
184669029 我qq 不过我还是很水的😅
